# Generated by Django 4.2.19 on 2025-02-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
