# Generated by Django 4.2.18 on 2025-01-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('producer', models.CharField(max_length=50, verbose_name='Продюсер')),
                ('duration', models.IntegerField(verbose_name='Проделжительность')),
            ],
        ),
    ]
